[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    mrfaptastic/ESP32 HUB75 LED MATRIX PANEL DMA Display
    adafruit/Adafruit GFX Library
    adafruit/Adafruit BusIO
    ayushsharma82/ElegantOTA @ ^3.1.0
    bblanchon/ArduinoJson @ ^7.0.0
board_build.partitions = min_spiffs.csv
build_flags =
    -DELEGANTOTA_USE_ASYNC_WEBSERVER=0
